# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 14:08
from __future__ import unicode_literals

import Login.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreceiver',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='userreceiver',
            managers=[
                ('objects', Login.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='userreceiver',
            old_name='admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userreceiver',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userreceiver',
            name='staff',
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
