# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20171202_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreceiver',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='userreceiver',
            name='passWordHashed',
            field=models.CharField(max_length=255, null=True, verbose_name='passHashed'),
        ),
        migrations.AlterField(
            model_name='userreceiver',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
